import { STATUS_LABELS } from '@/lib/constants';

export const copy = {
  brand: {
    name: 'TicketAnglo',
    initials: 'T',
    institution: 'Colégio Anglo Pindamonhangaba',
    description: 'Sistema interno de gestão de demandas do Colégio Anglo Pindamonhangaba.',
    restrictedAccess: 'Acesso restrito à equipe interna do colégio.',
  },
  common: {
    cancel: 'Cancelar',
    close: 'Fechar',
    confirm: 'Confirmar',
    save: 'Salvar',
    delete: 'Excluir',
    edit: 'Editar',
    clear: 'Limpar',
    unknown: 'Desconhecido',
    removedUser: 'Usuário removido',
    system: 'Sistema',
    empty: 'Vazio',
    dropHere: 'Soltar aqui',
  },
  metadata: {
    dashboard: 'Painel',
    tickets: 'Demandas',
    kanban: 'Quadro',
    settings: 'Configurações',
  },
  auth: {
    labels: {
      username: 'Usuário',
      password: 'Senha',
    },
    placeholders: {
      username: 'seu.usuario',
      password: '••••••••',
    },
    buttons: {
      submit: 'Entrar',
      pending: 'Entrando...',
      signOut: 'Sair',
    },
    errors: {
      invalidCredentials: 'Usuário ou senha incorretos.',
      permissionDenied: 'Sem permissão.',
    },
    menu: {
      userMenu: 'Menu do usuário',
      admin: 'Administrador',
      changeOwnPassword: 'Alterar minha senha',
    },
    credentials: {
      username: 'Usuário',
      password: 'Senha',
    },
  },
  validation: {
    invalidData: 'Dados inválidos.',
    invalidComment: 'Comentário inválido.',
    invalidField: 'Campo inválido.',
    invalidSubcategory: 'Subcategoria inválida.',
    invalidTicket: 'Ticket não encontrado.',
    invalidUser: 'Usuário não encontrado.',
    usernamePattern: 'Use apenas letras minúsculas, números, ponto, hífen ou sublinhado.',
    usernameExists: 'Este usuário já existe.',
    passwordTooShort: 'A senha precisa ter ao menos 8 caracteres.',
    passwordMismatch: 'As senhas não coincidem.',
    passwordFailed: 'Não foi possível alterar a senha.',
    createUserFailed: 'Não foi possível criar o usuário.',
    missingDatabaseUrl: 'DATABASE_URL não foi configurada.',
  },
  nav: {
    links: {
      dashboard: 'Painel',
      kanban: 'Quadro',
      tickets: 'Demandas',
      settings: 'Configurações',
    },
    search: 'Buscar',
    commandShortcut: 'Ctrl K',
    newTicket: 'Nova demanda',
    mobileMenu: 'Menu',
    signOutWithName: (name: string) => `Sair - ${name}`,
  },
  theme: {
    light: 'Tema claro',
    dark: 'Tema escuro',
    switchToLight: 'Mudar para tema claro',
    switchToDark: 'Mudar para tema escuro',
  },
  commandPalette: {
    title: 'Buscar ação ou página',
    placeholder: 'O que você quer fazer?',
    noResults: (query: string) => `Nenhuma ação encontrada para "${query}".`,
    groups: {
      actions: 'Ações',
      navigation: 'Ir para',
    },
    actions: {
      newTicket: 'Registrar nova demanda',
      dashboard: 'Painel',
      kanban: 'Quadro Kanban',
      tickets: 'Lista de demandas',
      settings: 'Configurações',
    },
    hints: {
      navigate: 'navegar',
      select: 'selecionar',
      escape: 'esc',
    },
    keywords: {
      newTicket: 'novo registrar criar ticket demanda',
    },
  },
  dashboard: {
    greeting: {
      morning: (name: string) => `Bom dia, ${name}`,
      afternoon: (name: string) => `Boa tarde, ${name}`,
      evening: (name: string) => `Boa noite, ${name}`,
      fallbackName: 'Usuário',
    },
    stats: {
      openTi: 'Abertos TI',
      openMkt: 'Abertos MKT',
      urgent: 'Urgentes',
      waiting: 'Aguardando',
      resolvedWeek: 'Resolvidos na semana',
      allClear: 'Tudo em ordem.',
      noUrgencies: 'Sem urgências.',
      noBlocks: 'Sem bloqueios.',
      noneThisWeek: 'Nada ainda esta semana.',
    },
    recent: {
      title: 'Últimas demandas',
      description: 'Atividade mais recente do colégio',
      viewAll: 'Ver todas',
      emptyTitle: 'Nenhuma demanda registrada ainda',
      emptyHint: 'Pressione N para registrar a primeira.',
    },
  },
  tickets: {
    page: {
      title: 'Demandas',
      description: 'Filtre, busque e gerencie todas as demandas do colégio.',
    },
    table: {
      headers: {
        code: 'Código',
        area: 'Área',
        title: 'Demanda',
        priority: 'Prioridade',
        status: 'Status',
        createdAt: 'Criada',
        author: 'Autor',
        subcategory: 'Subcategoria',
      },
      searchPlaceholder: 'Buscar por código, título ou descrição...',
      clearSearch: 'Limpar busca',
      clearFilters: 'Limpar filtros',
      allAreas: 'Todas as áreas',
      allStatuses: 'Todos os status',
      allPriorities: 'Todas',
      allAssignees: 'Todos responsáveis',
      unassigned: 'Sem responsável',
      exportCsv: 'Exportar CSV',
      count: (total: number) => `${total} ${total === 1 ? 'demanda' : 'demandas'}`,
      emptyFiltered: 'Nenhuma demanda encontrada com esses filtros',
      emptyDefault: 'Nenhuma demanda registrada',
      emptyFilterHint: 'Ajuste os filtros ou limpe a busca.',
      emptyDefaultHint: 'Pressione N para registrar a primeira.',
      byAuthor: (name: string) => `por ${name}`,
      fileNamePrefix: 'tickets',
      pagination: {
        previous: 'Anterior',
        next: 'Próxima',
        page: (page: number, total: number) => `Página ${page} de ${total}`,
        range: (start: number, end: number, total: number) => `${start}-${end} de ${total}`,
      },
    },
    form: {
      title: 'Nova demanda',
      description: 'Registre uma solicitação para TI ou Marketing.',
      fields: {
        area: 'Área',
        subcategory: 'Subcategoria',
        title: 'Título',
        priority: 'Prioridade',
        origin: 'Origem',
        assignee: 'Responsável inicial',
        description: 'Descrição',
      },
      placeholders: {
        subcategory: 'Selecione...',
        title: 'Ex: Projetor da sala 12 não liga',
        origin: 'Ex: WhatsApp da Profa. Júlia',
        assignee: 'Sem responsável',
        description: 'Detalhes do problema, contexto, prazo desejado...',
      },
      helper: {
        origin: 'De onde a solicitação veio: pessoa, canal, sala.',
      },
      validation: {
        title: 'Dê um título à demanda',
        titleMax: 'Máximo de 80 caracteres',
        subcategory: 'Escolha uma subcategoria',
      },
      advanced: {
        open: 'Opções avançadas',
        close: 'Ocultar opções avançadas',
      },
      actions: {
        submit: 'Registrar demanda',
      },
      toast: {
        created: (code: string) => `Demanda ${code} registrada.`,
        open: 'Abrir',
      },
    },
    detail: {
      back: 'Todas as demandas',
      description: 'Descrição',
      noDescription: 'Sem descrição detalhada.',
      actionsTitle: 'Ações',
      statusTitle: 'Mudar status',
      assigneeTitle: 'Responsável',
      assignToMe: 'Atribuir a mim',
      noAssignee: 'Sem responsável',
      priorityTitle: 'Prioridade',
      metaTitle: 'Detalhes',
      openedBy: 'Aberta por',
      resolvedAt: 'Resolvida em',
      archivedConfirmTitle: 'Arquivar esta demanda?',
      archivedConfirmDescription:
        'Demandas arquivadas saem do quadro Kanban e da lista padrão. Você pode desarquivar depois.',
      statusUpdated: (status: keyof typeof STATUS_LABELS) =>
        `Status alterado para "${STATUS_LABELS[status]}".`,
      assigneeRemoved: 'Responsável removido.',
      assigneeUpdated: (name: string) => `Atribuído a ${name}.`,
      priorityUpdated: 'Prioridade atualizada.',
      editDetails: 'Editar detalhes',
      detailsUpdated: 'Detalhes atualizados.',
      deleteTicket: 'Excluir demanda',
      deleteTicketTitle: (code: string) => `Excluir ${code}?`,
      deleteTicketDescription:
        'A demanda, os comentários e o histórico serão removidos definitivamente. Use apenas para registros criados por engano.',
      ticketDeleted: (code: string) => `${code} foi excluída.`,
      statusActions: {
        aberto: 'Reabrir',
        em_andamento: 'Iniciar atendimento',
        aguardando: 'Marcar como aguardando',
        resolvido: 'Marcar como resolvido',
        arquivado: 'Arquivar',
      },
    },
    comments: {
      title: 'Comentários',
      count: (total: number) => `${total} ${total === 1 ? 'comentário' : 'comentários'}`,
      anonymous: 'Anônimo',
      placeholder: 'Atualização, dúvida ou observação...',
      shortcut: 'Ctrl + Enter para enviar',
      submit: 'Comentar',
      actionsFor: (name: string) => `Ações do comentário de ${name}`,
      edit: 'Editar comentário',
      delete: 'Excluir comentário',
      saveEdit: 'Salvar edição',
      editPlaceholder: 'Atualize o comentário...',
      edited: 'Comentário atualizado.',
      deleted: 'Comentário excluído.',
      deleteTitle: 'Excluir comentário?',
      deleteDescription: 'Esta ação remove o comentário definitivamente.',
    },
    history: {
      title: 'Histórico de alterações',
      noneValue: 'ninguém',
      changed: 'alterou',
      from: 'de',
      to: 'para',
    },
  },
  kanban: {
    page: {
      title: 'Quadro',
      description: 'Arraste demandas entre as colunas para mover seu status.',
    },
    filters: {
      area: 'Área',
      assignee: 'Responsável',
      allAreas: 'Todas as áreas',
      allAssignees: 'Todos responsáveis',
    },
    emptyTitle: 'Nenhuma demanda no quadro',
    emptyHint: 'Pressione N para registrar a primeira.',
    moved: (code: string, status: keyof typeof STATUS_LABELS) =>
      `${code} movido para "${STATUS_LABELS[status]}".`,
  },
  users: {
    page: {
      title: 'Configurações',
      description: 'Gerencie usuários, permissões e a sua conta.',
      usersTab: 'Usuários',
      accountTab: 'Minha conta',
      teamTitle: (total: number) => `Equipe (${total})`,
      teamDescription: 'Acesso, permissões, senha e remoção segura.',
      addTitle: 'Adicionar novo usuário',
      addDescription: 'Crie credenciais para um novo membro da equipe.',
    },
    roles: {
      admin: 'Administrador',
      user: 'Usuário',
      adminShort: 'Admin',
    },
    status: {
      inactive: 'Inativo',
      you: 'Você',
      joinedAt: (username: string, date: string) => `@${username} ingressou em ${date}`,
    },
    form: {
      username: 'Usuário',
      displayName: 'Nome exibido',
      password: 'Senha provisória',
      isAdmin: 'Conceder acesso de administrador',
      placeholders: {
        username: 'nome.sobrenome',
        displayName: 'Ex: Natália Costa',
        password: 'Mínimo 8 caracteres',
      },
      helper: 'O usuário poderá alterar a própria senha após o primeiro acesso.',
      add: 'Adicionar',
      generatePassword: 'Gerar',
      copyPassword: 'Copiar senha',
      copiedPassword: 'Senha copiada.',
      showPassword: 'Mostrar senha',
      hidePassword: 'Ocultar senha',
      added: (name: string) => `${name} foi adicionado à equipe.`,
    },
    list: {
      actionsFor: (name: string) => `Ações para ${name}`,
      edit: 'Editar usuário',
      resetPassword: 'Redefinir senha',
      makeAdmin: 'Tornar administrador',
      removeAdmin: 'Remover administrador',
      deactivate: 'Desativar acesso',
      reactivate: 'Reativar acesso',
      delete: 'Excluir usuário',
      deactivated: (name: string) => `${name} foi desativado.`,
      reactivated: (name: string) => `${name} foi reativado.`,
      deleted: (name: string) => `${name} foi excluído.`,
      adminGranted: (name: string) => `${name} agora é administrador.`,
      adminRevoked: (name: string) => `${name} deixou de ser administrador.`,
      updated: (name: string) => `${name} foi atualizado.`,
      deactivateTitle: (name: string) => `Desativar ${name}?`,
      deactivateDescription:
        'O usuário não poderá entrar no sistema, mas todo o histórico será preservado. Você pode reativar depois.',
      deleteTitle: (name: string) => `Excluir ${name}?`,
      deleteDescription:
        'A conta será removida definitivamente. Demandas, comentários e histórico continuam preservados como registros de usuário removido.',
      roleTitle: (name: string, isAdmin: boolean) =>
        isAdmin ? `Remover administração de ${name}?` : `Tornar ${name} administrador?`,
      roleDescription: 'A alteração de permissão passa a valer no próximo acesso do usuário.',
    },
    editDialog: {
      title: 'Editar usuário',
      description: 'Atualize nome, identificador e permissão.',
      submit: 'Salvar usuário',
    },
    errors: {
      cannotDeactivateSelf: 'Você não pode desativar a própria conta.',
      cannotDeleteSelf: 'Você não pode excluir a própria conta.',
      cannotRemoveLastAdmin: 'Mantenha ao menos um administrador ativo.',
    },
    password: {
      changeMine: 'Alterar minha senha',
      reset: 'Redefinir senha',
      descriptionSelf: 'Defina uma nova senha para acessar sua conta.',
      descriptionUser: (name: string) => `Defina uma nova senha para ${name}.`,
      newPassword: 'Nova senha',
      confirmPassword: 'Confirmar nova senha',
      placeholder: 'Mínimo 8 caracteres',
      confirmPlaceholder: 'Digite novamente',
      submit: 'Salvar nova senha',
      selfUpdated: 'Senha atualizada com sucesso.',
      userUpdated: (name: string) => `Senha de ${name} atualizada.`,
    },
    account: {
      passwordTitle: 'Senha',
      passwordDescription: 'Atualize sua senha periodicamente para manter a conta segura.',
      changePassword: 'Alterar senha',
    },
  },
  api: {
    unauthorized: 'Não autorizado.',
    missingBootstrapConfig:
      'Configure BOOTSTRAP_ADMIN_USERNAME, BOOTSTRAP_ADMIN_DISPLAY_NAME e BOOTSTRAP_ADMIN_PASSWORD.',
    bootstrapOk: 'Administrador sincronizado.',
  },
} as const;
